AllCops:
  TargetRubyVersion: 2.6

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false  

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40
Metrics/ClassLength:
  Max: 300
Metrics/BlockLength:
  Max: 50
